name: '.NET Build'
description: 'Builds and tests .NET projects'

inputs:
  dotnet-version:
    description: '.NET version'
    required: false
    default: '9.0.x'
  build-configuration:
    description: 'Build configuration (e.g. Debug, Release)'
    required: false
    default: 'Release'
  build-filter:
    description: 'Build artifact (e.g. path to project / solution or filter (**/*.csproj)'
    required: false
    default: '**/*.csproj'
  test-filter:
    description: 'Build artifact (e.g. path to project / solution or filter (**/*.csproj)'
    required: false
    default: '**/*[Tt]ests/*.csproj'
    
runs:
  using: composite
  steps:
  - name: Setup .NET
    uses: actions/setup-dotnet@v5
    with:
      dotnet-version: ${{ inputs.dotnet-version }}

  - name: Restore dependencies
    shell: bash
    run: dotnet restore ${{ input.build-filter }}

  - name: Build
    shell: bash
    run: dotnet build ${{ input.build-filter }} --configuration ${{ input.build-configuration }} --no-restore

  - name: Test
    shell: bash
    run: dotnet test ${{ input.test-filter }} --configuration ${{ input.build-configuration }} --no-build --verbosity normal
